
MORNING_SESSION_DURATION = 180
NOON_SESSION_DURATION = 240
MORNING_START_TIME = [9, 0, 0]
NOON_START_TIME = [13, 0, 0]
LUNCH_SESSION_DURATION = 60
NETWORKING_SESSION_DURATION = 60
LUNCH_START_TIME = [12, 0, 0]
LUNCH_SLOT_DURATION = 60
NETWORKING_SLOT_DURATION = 60

